### ISSUE TITLE
so many redirections

### ISSUE THREAD

**Issue by sergiocazzolato** [OpenTMI/opentmi#32]
I started the service with 
> npm start -- --https

Then, when I check if the service is up with 
> wget https://127.0.0.1:3000 --no-check-certificate

I get: 
--2017-04-20 02:14:32--  https://127.0.0.1:3000/
Connecting to 127.0.0.1:3000... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://127.0.0.1:3000/ [following]
...
--2017-04-20 02:14:32--  https://127.0.0.1:3000/
Reusing existing connection to 127.0.0.1:3000.
HTTP request sent, awaiting response... 302 Found
Location: https://127.0.0.1:3000/ [following]
20 redirections exceeded.

I see the same when I try to access through the web browser

**Comment by jupe** [comment]
Interesting. I cannot reproduce this, perhaps some changes fix this already.

```
bash$ wget https://127.0.0.1:3000 --no-check-certificate
--2017-06-27 08:45:58--  https://127.0.0.1:3000/
Connecting to 127.0.0.1:3000... connected.
WARNING: cannot verify 127.0.0.1's certificate, issued by ‘O=Internet Widgits Pty Ltd,ST=Some-State,C=FI’:
  Self-signed certificate encountered.
    WARNING: certificate common name ‘’ doesn't match requested host name ‘127.0.0.1’.
HTTP request sent, awaiting response... 200 OK
Length: 12251 (12K) [text/html]
Saving to: ‘index.html.1’

index.html.1                                           100%[==========================================================================================================================>]  11.96K  --.-KB/s    in 0.001s  

2017-06-27 08:45:58 (12.9 MB/s) - ‘index.html.1’ saved [12251/12251]
```

**Comment by jupe** [comment]
Probably this is not an issue anynore. If you can reproduce with latest version please raise new ticket.
