### ISSUE TITLE
[default-gui] Addon load failed

### ISSUE THREAD

**Issue by estoel81** [OpenTMI/opentmi#96]
### Description
- Type: Bug

---------------------------------------------------------------
## Bug

**opentmi version**
"name": "OpenTMI",
"version": "0.4.1",

"name": "opentmi-default-gui",
"version": "0.1.0",

**node.js version**
(`node -v&&node -p process.versions.v8`)
v8.1.4
5.8.283.41

**Expected Behavior**
npm start should start the gui

**Actual Behavior**
loading default-gui is failed

`info: <Master> 24603 is running
info: <Worker#1> Process: 24605 started
info: <Worker#1> Connecting to MongoDB: mongodb://localhost/opentmi_dev
info: <Worker#1> [INFO-Server:24605] 1507036021037 server localhost:27017 fired event connect out with message [object Object] type=info, message=server localhost:27017 fired event connect out with message [object Object], className=Server, pid=24605, date=1507036021037
info: <Worker#1> [INFO-Server:24605] 1507036021056 server localhost:27017 connected with ismaster [{"ismaster":true,"maxBsonObjectSize":16777216,"maxMessageSizeBytes":48000000,"maxWriteBatchSize":1000,"localTime":"2017-10-03T13:07:01.047Z","maxWireVersion":5,"minWireVersion":0,"readOnly":false,"ok":1}] type=info, message=server localhost:27017 connected with ismaster [{"ismaster":true,"maxBsonObjectSize":16777216,"maxMessageSizeBytes":48000000,"maxWriteBatchSize":1000,"localTime":"2017-10-03T13:07:01.047Z","maxWireVersion":5,"minWireVersion":0,"readOnly":false,"ok":1}], className=Server, pid=24605, date=1507036021056
info: <Worker#1> Connected to MongoDB: mongodb://localhost/opentmi_dev
info: <Worker#1> Registering models..
To create a new ObjectId please try `Mongoose.Types.ObjectId` instead of using `Mongoose.Schema.ObjectId`.
info: <Worker#1> Adding Routers...
info: <Worker#1> Loading addons...
info: <Worker#1> Admin Users: admin
error: <Worker#1> [default-gui] Addon load failed.
[default-gui] Load failed.
 └ message   : Cannot read property 'on' of undefined`

![screen shot 2017-10-03 at 15 07 55](https://user-images.githubusercontent.com/17541712/31126647-af5d07fe-a84c-11e7-907a-d5acd05857bb.png)

**Steps to Reproduce**
npm start

**Comment by jupe** [comment]
default-gui is not yet updated against new opentmi addon architectures unfortunately (opentmi 0.4.x). i’ll update it as soon as i’ve time..

**Comment by jupe** [comment]
Could you try this one: https://github.com/OpenTMI/opentmi-default-gui/pull/22

**Comment by jupe** [comment]
now there should be working version in head-of master. Will be released in next patch release v0.4.2.

**Comment by estoel81** [comment]
Yeah it works!
